apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - deployment
      matchRules:
        - type: and
          matches:
            - type: pattern
              pattern: ".+"
              properties: [name]
              mode: substring
            - type: pattern
              pattern: "kustomize.toolkit.fluxcd.io/name"
              properties: [metadata/labels]
              mode: substring
            # - resourceType: variables
            #   type: pattern
            #   pattern: "github"
            #   properties: [custom/gitops_provider]
            #   mode: substring
      slxs:
        - baseName: depl-gh-fix
          levelOfDetail: detailed
          qualifiers: ["namespace", "cluster"]
          baseTemplateName: k8s-deployment-gitops-gh-remediate
          outputItems:
            - type: slx
            - type: runbook
              templateName: k8s-deployment-gitops-gh-remediate-taskset.yaml
