name: Run E2E Tests
on:
  workflow_dispatch:
    inputs:
      runall:
        type: choice
        description: Test all codebundles found in workspace, regardless of changes?
        options: 
          - no
          - yes
  push: 
    branches: 
      - main
    paths: 
      - "codebundles/**.robot"
# TODO: add traced python dependency support

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: ${{ github.event.pull_request.base.ref }}
      - name: install deps
        run: |
          pip install requests
      - name: Run E2E Tests
        env:
          API_USER: ${{ secrets.API_USER }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          API_URL: https://backend-services.dev.project-468.com/api/v3
          WORKSPACE: ob-1-small
        run: |
          if [ "${{ github.event.inputs.runall }}" = "yes" ]; then
            python e2e.py --e2e_workspace=$WORKSPACE --papi_url=$API_URL --runall
          else
            python e2e.py --e2e_workspace=$WORKSPACE --papi_url=$API_URL
          fi
          